:sectnums:

== Source 1 : https://auth0.com/intro-to-iam/what-is-oauth-2

* OAuth : Open authorization
* provides consented access and restricts actions of what the client app can perform on resources on behalf of the user, without ever sharing the user's credentials
* OAuth 2.0 is an authorization protocol and NOT an authentication protocol
** it is designed primarily as a means of granting access to a set of resources, for example, remote APIs or user data.

* OAuth 2.0 uses Access Tokens.
An Access Token is a piece of data that represents the authorization to access resources on behalf of the end-user
** JSON Web Token (JWT) format is often used.
** Access tokens have expiration date

=== Components of OAuth-2.0

* Resource Owner : system / user that owns the protected resources and can grant access to them
* Client : system asking access to restricted resources
* Authorization server :
** This server receives requests from the Client for Access Tokens and issues them upon successful authentication and consent by the Resource Owner.
** The authorization server exposes two endpoints:
*** the Authorization endpoint, which handles the interactive authentication and consent of the user
*** Token endpoint, which is involved in a machine to machine interaction

* Resource server :
** A server that protects the user’s resources
** receives access requests from the Client
** Accepts and validates an Access Token from the Client and returns the appropriate resources to it.

=== Working

* before OAuth 2.0 can be used, the Client must acquire its own credentials, a _client id _ and client secret
* Using OAuth 2.0, access requests are initiated by the Client,

[plantuml]
----
@startuml JWTInjection

!include <c4/C4_Context.puml>
!include <c4/C4_Container.puml>

Person(user,'User')
Container(client,'Client APP')
Container(auth,'Auth Server')
Container(re,'Resource server')


Rel_D(client,auth , '1. Register and get client id and certificate | redirect url')
Rel_D(client,auth , '2. Request AUTH')
Rel_U(client,user , '3. REDIRECT: AUTH PAGE LINK (hosted by auth server)')
Rel_U(auth, client, '4. redirect using callback and passes the AUTH token')
Rel(user, auth, '5. credentials')
Rel(auth, client, '5. redirect + access_token')
Rel_D(client ,re, '6. token + request_resources')
Rel_U(re ,auth, '7. (optional) validate tokens like opaque token')







@enduml
----

* Once user is authorized, the auth server redirects the user to client applications via the callback url and also pass the AUTH token

=== Read backlogs

* Difference between oauth1 and 2
* JWT
** Is is same as access token ?
** What is authorization token vs access token
* What does it mean by consent without user credentials ?
* what is the difference between authorization endpoint and token endpoint
* How does resource server authenticate tokens from client ?
* What are oauth2 scopes ?

== Experiment

=== Accessing KITE API using OAuth2.0

==== Scope

* Host a callback URL on GCP project

1. create a python app that makes a call to get the login URL and redirects for login to KITE auth server
2. Upon a redirect to the login url , redirect to page that shows portfolio holdings


// [plantuml]
// ----
// @startuml
//
// [Resource Owner] as ro
//
// note as ron
// system that owns the protected resources
// and can grant access to them
// end note
//
// ro .. ron
//
// @enduml
// ----


